---
title: "2015896 - GEOMATICA BASICA"
format:
  html:
    include-before-body: helpers/remove-nav.html
    include-after-body: helpers/remove-title.html
---

# 📑 Course Brief

**Focus:** the focus of this course is introduce concepts, methods and tecniques used in geoinformation disciplines.

**How:** reading,  learning by doing and writing

# 🎯 Learning Objectives

- Understand the usefulness of geospatial data for supporting agronomy.
- Internalize basic concepts about geodesy, cartography, GIS, remote sensing, and geostatistics. 
- Be able to apply geospatial techniques for data collection, processing, visualization and analysis.
- Develop  critical spatial thinking.

# 🎯 Class Atendance Policy

Students are expected to attend all classes. Occasional absences due to illness are considered excused. Participation in university activities must be requested in advance.

# 🎯 Artificial Intelligence Policy

Students may use generative AI to support —not replace— their own thinking, effort, and style. In any case, the use of generative AI is permitted for up to 50% of the submitted work.

-----------------

**Select Academic Year/Term:**

<a href="2026/index.qmd">
    <button class="button-61">2026</button>
</a>

