---
title: "🗓️ Week 03 - Coordinate systems  and map projections"
---

In this week, we will cover the following topics:

**Theoretical topics**:

- the role of geodesy as a basis for earth datums
- how to calculate distances on a spherical earth
- the basic types of map projection
- the properties of common map projections
- the terminology of common coordinate systems
- how to use  a GIS to convert between coordinate systems 

**Practical exercises**:

Review coordinate systems's metadata 

Reproject vector and raster data

## 👨‍ Lecture Slides 

You can find the slides [here](https://docs.google.com/presentation/d/1teYd09bo9BH2CK0b3G9Z77jnxcDjmTJ-/edit?usp=sharing&ouid=101294548671143516389&rtpof=true&sd=true)

🎥 

## ‍🏫 QGIS Exercise

- Reproject vector and raster data in your *Proyecto 1* and *Proyecto 2* from EPSG:4326 to EPSG:9377

## ✍️ Coursework

🚧 In your  notebook,  answer the following questions 🚧

### Part 1
::: {.callout-important collapse=true}
1. What are the geometric parameters associated to the ellipsoid GRS 80?
2. What is the geoid?
3. What are the most important characteristics of the geoid?
:::

### Part 2
::: {.callout-important collapse=true}
4. What is a datum?
5. What is the datum MAGNA-SIRGAS?
6. Describe  the [Colombian map projection with Origen Nacional](https://rodolfofrancoweb.com/sig/proyecciones_y_sistemas_de_coordenadas/magna-sirgas-origen-nacional/) 

:::

### Part 3
::: {.callout-important collapse=true}
7. Explore [these tools](https://hanshack.com/geotools/)
:::


